# Mesh Integration Configuration  
# Defines how this device integrates with the mesh-infra repository

version: 3
integration_type: second_wave_deployment_target
parent_repo: mesh-infra
phase: 2_complete_awaiting_phase_2-8
rollout_order: 2  # WSL → Laptop → Hetzner

# Synchronization Settings
sync:
  # What this device reports to mesh-infra
  reports_to_parent:
    - device_status
    - connectivity_state
    - service_availability
    - resource_metrics
  
  # What this device receives from mesh-infra
  receives_from_parent:
    - network_policies
    - security_updates
    - service_discovery
    - routing_tables

# API Endpoints (when connected to mesh)
api:
  status_endpoint: http://laptop-hq.hq:9090/status
  metrics_endpoint: http://laptop-hq.hq:9090/metrics
  config_endpoint: http://laptop-hq.hq:9090/config

# Event Hooks
hooks:
  on_mesh_join:
    - ./scripts/register-with-hub.sh
    - ./scripts/sync-policies.sh
  on_mesh_leave:
    - ./scripts/cache-state.sh
  on_config_change:
    - ./scripts/apply-config.sh
  on_ansible_run:
    - ./scripts/ansible-readiness-check.sh

# Discovery Information
discovery:
  advertise:
    hostname: fedora-top
    mesh_name: laptop-hq
    services:
      - development_environment
      - ai_agent_host
    capabilities:
      - can_build
      - can_test
      - has_gpu: false
      - mobile: true

# State Management
state:
  local_cache: ./state/current.json
  remote_sync: hetzner-hq:/mesh/nodes/laptop-hq/state
  sync_interval: 300  # seconds
  offline_grace_period: 3600  # seconds before marked offline
  
# Ansible Integration Status
ansible:
  status: active
  control_node: hetzner-hq
  last_run: "2025-09-07"
  ssh_key_authorized: true
  passwordless_sudo: true
  ready_for_management: true