# Phase 3 Readiness Configuration
# File Synchronization with Syncthing

version: 1
phase: 3_ready
implementation: syncthing

# This Laptop's Phase 3 Capabilities
laptop_role:
  type: full_participant
  storage_contribution: true
  sync_performance: high
  mobility_aware: true

# Syncthing Configuration
syncthing:
  ready: true
  installation: pending_mesh_wide_deployment
  capabilities:
    - high_bandwidth_sync
    - mobile_sync_handling
    - selective_sync_support
    - conflict_resolution

# Sync Participation
sync_roles:
  - name: development_projects
    path: "/home/verlyn13/Projects"
    sync_type: selective
    participants: [hetzner-hq, laptop-hq, wsl-hq]
    priority: high
    
  - name: configuration_files
    path: "/home/verlyn13/.config"
    sync_type: selective
    participants: [laptop-hq, wsl-hq]
    priority: medium
    
  - name: shared_documents
    path: "/home/verlyn13/Documents/Shared"
    sync_type: full
    participants: [hetzner-hq, laptop-hq, wsl-hq]
    priority: low

# Device Considerations
device_constraints:
  storage_available: high  # Ample disk space
  bandwidth_variable: true  # Roaming device
  power_aware: true  # Battery considerations
  network_changes: frequent  # Different WiFi networks

# Integration with Other Nodes
mesh_integration:
  with_hetzner_hq:
    role: backup_target
    sync_frequency: continuous_when_online
    storage_role: secondary
    
  with_wsl_hq:
    role: development_companion
    sync_focus: projects_and_configs
    considerations: [limited_storage, corporate_network]

# Sync Strategies
strategies:
  online_mode:
    sync_type: real_time
    bandwidth_limit: none
    conflict_resolution: latest_wins
    
  roaming_mode:
    sync_type: scheduled
    bandwidth_limit: conservative
    offline_changes: queue_for_sync
    
  low_battery_mode:
    sync_type: critical_only
    bandwidth_limit: minimal
    defer_large_files: true

# Phase 3 Preparation Status
preparation:
  disk_space: sufficient
  network_config: mesh_ready
  sync_policies: defined
  conflict_handling: planned
  security_model: ready

# Waiting Conditions
waiting_for:
  - wsl_hq_deployment
  - mesh_wide_syncthing_setup
  - phase3_implementation_signal

# Success Metrics
success_criteria:
  - sync_established_all_nodes: 3/3
  - file_consistency_maintained: true
  - performance_acceptable: >50MB/s_local
  - mobile_sync_functional: true
  - conflict_resolution_working: true